local Pipeline(name, image) = {
  kind: "pipeline",
  name: name,
  platform:
    arch: "arm64"
  steps: [
    {
      name: "test",
      image: image,
      commands: [
        "pip install -r requirements.txt"
      ]
      environment: 
        TOXENV: "py38"
        LIBRESSL: "2.9.2"        
    }
  ]
};

[
  Pipeline("test", "python:3.8"),
]
