# Test file
#kind: pipeline
#name: test-on-arm64-py
#platform:
#  arch: arm64
#steps:
#- name: test
#  image: python:3.8
#  commands:
#  - .travis/install.sh
#  - ./.travis/run.sh
#  environment:
#    TOXENV: py38 
#    LIBRESSL: 2.9.2

kind: pipeline
name: test-on-arm64-docker
platform:
  arch: arm64
steps:
- name: test
  image: docker:dind
  commands:
  - .travis/install.sh
  - ./.travis/run.sh
  environment:
    TOXENV: py38
    DOCKER: 'pyca/cryptography-runner-bullseye'
