# Test file
kind: pipeline
name: test-on-arm64
platform:
  arch: arm64
steps:
- name: test
  image: python:3.8
  commands:
  - .travis/install.sh
  - ./.travis/run.sh
  environment:
    TOXENV: py38 
    LIBRESSL: 2.9.2

kind: pipeline
type: docker
name: test-on-arm64
platform:
  arch: arm64
steps:
- name: test
  image: python:3.8
  commands:
  - .travis/install.sh
  - ./.travis/run.sh
  environment:
    TOXENV: py38
    DOCKER: 'pyca/cryptography-runner-bullseye'
